export const data = {
    "results":[
        {
            "data":{
                "Data.IndividualTypeProperties.DataSourceOrganisationID":"srn:master-data/Organisation:TNO:",
                "Data.IndividualTypeProperties.VerticalMeasurements":[
                    {
                        "VerticalCRSID":"srn:reference-data/VerticalCRS:MSL:",
                        "VerticalMeasurementID":"Kelly Bushing",
                        "VerticalMeasurementPathID":"srn:reference-data/VerticalMeasurementPath:Elevation:",
                        "VerticalMeasurementTypeID":"srn:reference-data/VerticalMeasurementType:Kelly Bushing:",
                        "VerticalMeasurement":36.6,
                        "VerticalMeasurementUnitOfMeasureID":"srn:reference-data/UnitOfMeasure:M:"
                    }
                ],
                "SpatialLocation":[
                    "Coordinates=['x=3.51906683, y=55.68101428'], SpatialGeometryTypeID='srn:reference-data/SpatialGeometryType:Point:', VerticalCRSID='srn:reference-data/VerticalCRS:MSL:', HorizontalCRSID='srn:reference-data/HorizontalCRS:WGS84:', HeightAboveGroundLevelUOMID='srn:reference-data/UnitOfMeasure:M:'"
                ],
                "Data.IndividualTypeProperties.FacilityName":"A05-01",
                "WellName":"Astra-01",
                "Data.IndividualTypeProperties.FacilityNameAlias":[
                    {
                        "AliasName":"A05-01",
                        "AliasNameTypeID":"srn:reference-data/AliasNameType:Name:"
                    },
                    {
                        "AliasName":"8438",
                        "AliasNameTypeID":"srn:reference-data/AliasNameType:UWI:"
                    }
                ],
                "Data.IndividualTypeProperties.CountryID":"srn:master-data/GeopoliticalEntity:Netherlands:",
                "Data.IndividualTypeProperties.SpatialLocation":[
                    {
                        "HorizontalCRSID":"srn:reference-data/HorizontalCRS:WGS84:",
                        "VerticalCRSID":"srn:reference-data/VerticalCRS:MSL:",
                        "HeightAboveGroundLevelUOMID":"srn:reference-data/UnitOfMeasure:M:",
                        "Coordinates":[
                            {
                                "x":3.51906683,
                                "y":55.68101428
                            }
                        ],
                        "SpatialGeometryTypeID":"srn:reference-data/SpatialGeometryType:Point:"
                    }
                ],
                "UWI":"8438",
                "Data.IndividualTypeProperties.FacilityOperator":[
                    {
                        "FacilityOperatorOrganisationID":"srn:master-data/Organisation:Amarada Hess:"
                    }
                ],
                "Data.IndividualTypeProperties.OperatingEnvironmentID":"srn:reference-data/WellOperatingEnvironment:OFF:",
                "FacilityEvent":[
                    "FacilityEventTypeID='srn:reference-data/FacilityEventType:SPUD:', EffectiveDateTime='1999-06-03T00:00:00'",
                    "FacilityEventTypeID='srn:reference-data/FacilityEventType:DRILLING FINISH:', EffectiveDateTime='1999-07-02T00:00:00'"
                ],
                "ResourceID":"srn:master-data/Well:8438:",
                "Data.IndividualTypeProperties.DefaultVerticalMeasurementID":"Kelly Bushing",
                "Data.IndividualTypeProperties.BlockID":"srn:master-data/GeopoliticalEntity:A05:",
                "x-geojson":{
                    "geometries":[
                        {
                            "coordinates":[
                                3.519067,
                                55.781014
                            ],
                            "type":"point"
                        }
                    ],
                    "type":"geometrycollection"
                },
                "ResourceSecurityClassification":"srn:reference-data/ResourceSecurityClassification:RESTRICTED:",
                "ResourceTypeID":"srn:type:master-data/Well:",
                "GeoLocation":{
                    "lon":3.519067,
                    "lat":55.681014
                },
                "Data.IndividualTypeProperties.FacilityEvent":[
                    {
                        "EffectiveDateTime":"1999-06-03T00:00:00",
                        "FacilityEventTypeID":"srn:reference-data/FacilityEventType:SPUD:"
                    },
                    {
                        "EffectiveDateTime":"1999-07-02T00:00:00",
                        "FacilityEventTypeID":"srn:reference-data/FacilityEventType:DRILLING FINISH:"
                    }
                ],
                "SpudDate":"1999-06-03T00:00:00+0000",
                "Data.IndividualTypeProperties.FacilityState":[
                    {
                        "FacilityStateTypeID":"srn:reference-data/FacilityStateType:Abandoned:"
                    }
                ]
            },
            "kind":"opendes:osdu:well-master:0.2.1",
            "namespace":"opendes:osdu",
            "legal":{
                "legaltags":[
                    "opendes-public-usa-dataset-1"
                ],
                "otherRelevantDataCountries":[
                    "US"
                ],
                "status":"compliant"
            },
            "id":"opendes:doc:1934c51244af4952a7b60c41173e174e",
            "acl":{
                "viewers":[
                    "data.default.viewers@opendes.testing.com"
                ],
                "owners":[
                    "data.default.owners@opendes.testing.com"
                ]
            },
            "type":"well-master",
            "version":1587773484611490
        },
{
                "data":{
                    "Data.IndividualTypeProperties.DataSourceOrganisationID":"srn:master-data/Organisation:TNO:",
                    "Data.IndividualTypeProperties.VerticalMeasurements":[
                        {
                            "VerticalCRSID":"srn:reference-data/VerticalCRS:MSL:",
                            "VerticalMeasurementID":"Kelly Bushing",
                            "VerticalMeasurementPathID":"srn:reference-data/VerticalMeasurementPath:Elevation:",
                            "VerticalMeasurementTypeID":"srn:reference-data/VerticalMeasurementType:Kelly Bushing:",
                            "VerticalMeasurement":36.6,
                            "VerticalMeasurementUnitOfMeasureID":"srn:reference-data/UnitOfMeasure:M:"
                        }
                    ],
                    "SpatialLocation":[
                        "Coordinates=['x=3.51906683, y=55.68101428'], SpatialGeometryTypeID='srn:reference-data/SpatialGeometryType:Point:', VerticalCRSID='srn:reference-data/VerticalCRS:MSL:', HorizontalCRSID='srn:reference-data/HorizontalCRS:WGS84:', HeightAboveGroundLevelUOMID='srn:reference-data/UnitOfMeasure:M:'"
                    ],
                    "Data.IndividualTypeProperties.FacilityName":"A05-01",
                    "WellName":"ABC-01",
                    "Data.IndividualTypeProperties.FacilityNameAlias":[
                        {
                            "AliasName":"A05-01",
                            "AliasNameTypeID":"srn:reference-data/AliasNameType:Name:"
                        },
                        {
                            "AliasName":"8438",
                            "AliasNameTypeID":"srn:reference-data/AliasNameType:UWI:"
                        }
                    ],
                    "Data.IndividualTypeProperties.CountryID":"srn:master-data/GeopoliticalEntity:Netherlands:",
                    "Data.IndividualTypeProperties.SpatialLocation":[
                        {
                            "HorizontalCRSID":"srn:reference-data/HorizontalCRS:WGS84:",
                            "VerticalCRSID":"srn:reference-data/VerticalCRS:MSL:",
                            "HeightAboveGroundLevelUOMID":"srn:reference-data/UnitOfMeasure:M:",
                            "Coordinates":[
                                {
                                    "x":3.51906683,
                                    "y":55.68101428
                                }
                            ],
                            "SpatialGeometryTypeID":"srn:reference-data/SpatialGeometryType:Point:"
                        }
                    ],
                    "UWI":"8438",
                    "Data.IndividualTypeProperties.FacilityOperator":[
                        {
                            "FacilityOperatorOrganisationID":"srn:master-data/Organisation:Amarada Hess:"
                        }
                    ],
                    "Data.IndividualTypeProperties.OperatingEnvironmentID":"srn:reference-data/WellOperatingEnvironment:OFF:",
                    "FacilityEvent":[
                        "FacilityEventTypeID='srn:reference-data/FacilityEventType:SPUD:', EffectiveDateTime='1999-06-03T00:00:00'",
                        "FacilityEventTypeID='srn:reference-data/FacilityEventType:DRILLING FINISH:', EffectiveDateTime='1999-07-02T00:00:00'"
                    ],
                    "ResourceID":"srn:master-data/Well:8438:",
                    "Data.IndividualTypeProperties.DefaultVerticalMeasurementID":"Kelly Bushing",
                    "Data.IndividualTypeProperties.BlockID":"srn:master-data/GeopoliticalEntity:A05:",
                    "x-geojson":{
                        "geometries":[
                            {
                                "coordinates":[
                                    3.719067,
                                    55.681014
                                ],
                                "type":"point"
                            }
                        ],
                        "type":"geometrycollection"
                    },
                    "ResourceSecurityClassification":"srn:reference-data/ResourceSecurityClassification:RESTRICTED:",
                    "ResourceTypeID":"srn:type:master-data/Well:",
                    "GeoLocation":{
                        "lon":3.519067,
                        "lat":55.681014
                    },
                    "Data.IndividualTypeProperties.FacilityEvent":[
                        {
                            "EffectiveDateTime":"1999-06-03T00:00:00",
                            "FacilityEventTypeID":"srn:reference-data/FacilityEventType:SPUD:"
                        },
                        {
                            "EffectiveDateTime":"1999-07-02T00:00:00",
                            "FacilityEventTypeID":"srn:reference-data/FacilityEventType:DRILLING FINISH:"
                        }
                    ],
                    "SpudDate":"1999-06-03T00:00:00+0000",
                    "Data.IndividualTypeProperties.FacilityState":[
                        {
                            "FacilityStateTypeID":"srn:reference-data/FacilityStateType:Abandoned:"
                        }
                    ]
                },
                "kind":"opendes:osdu:well-master:0.2.1",
                "namespace":"opendes:osdu",
                "legal":{
                    "legaltags":[
                        "opendes-public-usa-dataset-1"
                    ],
                    "otherRelevantDataCountries":[
                        "US"
                    ],
                    "status":"compliant"
                },
                "id":"opendes:doc:1934c51244af4952a7b60c41173e174e",
                "acl":{
                    "viewers":[
                        "data.default.viewers@opendes.testing.com"
                    ],
                    "owners":[
                        "data.default.owners@opendes.testing.com"
                    ]
                },
                "type":"well-master",
                "version":1587773484611490
            },
    {
                    "data":{
                        "Data.IndividualTypeProperties.DataSourceOrganisationID":"srn:master-data/Organisation:TNO:",
                        "Data.IndividualTypeProperties.VerticalMeasurements":[
                            {
                                "VerticalCRSID":"srn:reference-data/VerticalCRS:MSL:",
                                "VerticalMeasurementID":"Kelly Bushing",
                                "VerticalMeasurementPathID":"srn:reference-data/VerticalMeasurementPath:Elevation:",
                                "VerticalMeasurementTypeID":"srn:reference-data/VerticalMeasurementType:Kelly Bushing:",
                                "VerticalMeasurement":36.6,
                                "VerticalMeasurementUnitOfMeasureID":"srn:reference-data/UnitOfMeasure:M:"
                            }
                        ],
                        "SpatialLocation":[
                            "Coordinates=['x=3.51906683, y=55.68101428'], SpatialGeometryTypeID='srn:reference-data/SpatialGeometryType:Point:', VerticalCRSID='srn:reference-data/VerticalCRS:MSL:', HorizontalCRSID='srn:reference-data/HorizontalCRS:WGS84:', HeightAboveGroundLevelUOMID='srn:reference-data/UnitOfMeasure:M:'"
                        ],
                        "Data.IndividualTypeProperties.FacilityName":"A05-01",
                        "WellName":"Surp-01",
                        "Data.IndividualTypeProperties.FacilityNameAlias":[
                            {
                                "AliasName":"A05-01",
                                "AliasNameTypeID":"srn:reference-data/AliasNameType:Name:"
                            },
                            {
                                "AliasName":"8438",
                                "AliasNameTypeID":"srn:reference-data/AliasNameType:UWI:"
                            }
                        ],
                        "Data.IndividualTypeProperties.CountryID":"srn:master-data/GeopoliticalEntity:Netherlands:",
                        "Data.IndividualTypeProperties.SpatialLocation":[
                            {
                                "HorizontalCRSID":"srn:reference-data/HorizontalCRS:WGS84:",
                                "VerticalCRSID":"srn:reference-data/VerticalCRS:MSL:",
                                "HeightAboveGroundLevelUOMID":"srn:reference-data/UnitOfMeasure:M:",
                                "Coordinates":[
                                    {
                                        "x":3.51906683,
                                        "y":55.68101428
                                    }
                                ],
                                "SpatialGeometryTypeID":"srn:reference-data/SpatialGeometryType:Point:"
                            }
                        ],
                        "UWI":"8438",
                        "Data.IndividualTypeProperties.FacilityOperator":[
                            {
                                "FacilityOperatorOrganisationID":"srn:master-data/Organisation:Amarada Hess:"
                            }
                        ],
                        "Data.IndividualTypeProperties.OperatingEnvironmentID":"srn:reference-data/WellOperatingEnvironment:OFF:",
                        "FacilityEvent":[
                            "FacilityEventTypeID='srn:reference-data/FacilityEventType:SPUD:', EffectiveDateTime='1999-06-03T00:00:00'",
                            "FacilityEventTypeID='srn:reference-data/FacilityEventType:DRILLING FINISH:', EffectiveDateTime='1999-07-02T00:00:00'"
                        ],
                        "ResourceID":"srn:master-data/Well:8438:",
                        "Data.IndividualTypeProperties.DefaultVerticalMeasurementID":"Kelly Bushing",
                        "Data.IndividualTypeProperties.BlockID":"srn:master-data/GeopoliticalEntity:A05:",
                        "x-geojson":{
                            "geometries":[
                                {
                                    "coordinates":[
                                        3.519067,
                                        55.981014
                                    ],
                                    "type":"point"
                                }
                            ],
                            "type":"geometrycollection"
                        },
                        "ResourceSecurityClassification":"srn:reference-data/ResourceSecurityClassification:RESTRICTED:",
                        "ResourceTypeID":"srn:type:master-data/Well:",
                        "GeoLocation":{
                            "lon":3.519067,
                            "lat":55.681014
                        },
                        "Data.IndividualTypeProperties.FacilityEvent":[
                            {
                                "EffectiveDateTime":"1999-06-03T00:00:00",
                                "FacilityEventTypeID":"srn:reference-data/FacilityEventType:SPUD:"
                            },
                            {
                                "EffectiveDateTime":"1999-07-02T00:00:00",
                                "FacilityEventTypeID":"srn:reference-data/FacilityEventType:DRILLING FINISH:"
                            }
                        ],
                        "SpudDate":"1999-06-03T00:00:00+0000",
                        "Data.IndividualTypeProperties.FacilityState":[
                            {
                                "FacilityStateTypeID":"srn:reference-data/FacilityStateType:Abandoned:"
                            }
                        ]
                    },
                    "kind":"opendes:osdu:well-master:0.2.1",
                    "namespace":"opendes:osdu",
                    "legal":{
                        "legaltags":[
                            "opendes-public-usa-dataset-1"
                        ],
                        "otherRelevantDataCountries":[
                            "US"
                        ],
                        "status":"compliant"
                    },
                    "id":"opendes:doc:1934c51244af4952a7b60c41173e174e",
                    "acl":{
                        "viewers":[
                            "data.default.viewers@opendes.testing.com"
                        ],
                        "owners":[
                            "data.default.owners@opendes.testing.com"
                        ]
                    },
                    "type":"well-master",
                    "version":1587773484611490
                },
        {
                        "data":{
                            "Data.IndividualTypeProperties.DataSourceOrganisationID":"srn:master-data/Organisation:TNO:",
                            "Data.IndividualTypeProperties.VerticalMeasurements":[
                                {
                                    "VerticalCRSID":"srn:reference-data/VerticalCRS:MSL:",
                                    "VerticalMeasurementID":"Kelly Bushing",
                                    "VerticalMeasurementPathID":"srn:reference-data/VerticalMeasurementPath:Elevation:",
                                    "VerticalMeasurementTypeID":"srn:reference-data/VerticalMeasurementType:Kelly Bushing:",
                                    "VerticalMeasurement":36.6,
                                    "VerticalMeasurementUnitOfMeasureID":"srn:reference-data/UnitOfMeasure:M:"
                                }
                            ],
                            "SpatialLocation":[
                                "Coordinates=['x=3.51906683, y=55.68101428'], SpatialGeometryTypeID='srn:reference-data/SpatialGeometryType:Point:', VerticalCRSID='srn:reference-data/VerticalCRS:MSL:', HorizontalCRSID='srn:reference-data/HorizontalCRS:WGS84:', HeightAboveGroundLevelUOMID='srn:reference-data/UnitOfMeasure:M:'"
                            ],
                            "Data.IndividualTypeProperties.FacilityName":"A05-01",
                            "WellName":"Rodeo-01",
                            "Data.IndividualTypeProperties.FacilityNameAlias":[
                                {
                                    "AliasName":"A05-01",
                                    "AliasNameTypeID":"srn:reference-data/AliasNameType:Name:"
                                },
                                {
                                    "AliasName":"8438",
                                    "AliasNameTypeID":"srn:reference-data/AliasNameType:UWI:"
                                }
                            ],
                            "Data.IndividualTypeProperties.CountryID":"srn:master-data/GeopoliticalEntity:Netherlands:",
                            "Data.IndividualTypeProperties.SpatialLocation":[
                                {
                                    "HorizontalCRSID":"srn:reference-data/HorizontalCRS:WGS84:",
                                    "VerticalCRSID":"srn:reference-data/VerticalCRS:MSL:",
                                    "HeightAboveGroundLevelUOMID":"srn:reference-data/UnitOfMeasure:M:",
                                    "Coordinates":[
                                        {
                                            "x":3.51906683,
                                            "y":55.68101428
                                        }
                                    ],
                                    "SpatialGeometryTypeID":"srn:reference-data/SpatialGeometryType:Point:"
                                }
                            ],
                            "UWI":"8438",
                            "Data.IndividualTypeProperties.FacilityOperator":[
                                {
                                    "FacilityOperatorOrganisationID":"srn:master-data/Organisation:Amarada Hess:"
                                }
                            ],
                            "Data.IndividualTypeProperties.OperatingEnvironmentID":"srn:reference-data/WellOperatingEnvironment:OFF:",
                            "FacilityEvent":[
                                "FacilityEventTypeID='srn:reference-data/FacilityEventType:SPUD:', EffectiveDateTime='1999-06-03T00:00:00'",
                                "FacilityEventTypeID='srn:reference-data/FacilityEventType:DRILLING FINISH:', EffectiveDateTime='1999-07-02T00:00:00'"
                            ],
                            "ResourceID":"srn:master-data/Well:8438:",
                            "Data.IndividualTypeProperties.DefaultVerticalMeasurementID":"Kelly Bushing",
                            "Data.IndividualTypeProperties.BlockID":"srn:master-data/GeopoliticalEntity:A05:",
                            "x-geojson":{
                                "geometries":[
                                    {
                                        "coordinates":[
                                            3.919067,
                                            55.681014
                                        ],
                                        "type":"point"
                                    }
                                ],
                                "type":"geometrycollection"
                            },
                            "ResourceSecurityClassification":"srn:reference-data/ResourceSecurityClassification:RESTRICTED:",
                            "ResourceTypeID":"srn:type:master-data/Well:",
                            "GeoLocation":{
                                "lon":3.519067,
                                "lat":55.681014
                            },
                            "Data.IndividualTypeProperties.FacilityEvent":[
                                {
                                    "EffectiveDateTime":"1999-06-03T00:00:00",
                                    "FacilityEventTypeID":"srn:reference-data/FacilityEventType:SPUD:"
                                },
                                {
                                    "EffectiveDateTime":"1999-07-02T00:00:00",
                                    "FacilityEventTypeID":"srn:reference-data/FacilityEventType:DRILLING FINISH:"
                                }
                            ],
                            "SpudDate":"1999-06-03T00:00:00+0000",
                            "Data.IndividualTypeProperties.FacilityState":[
                                {
                                    "FacilityStateTypeID":"srn:reference-data/FacilityStateType:Abandoned:"
                                }
                            ]
                        },
                        "kind":"opendes:osdu:well-master:0.2.1",
                        "namespace":"opendes:osdu",
                        "legal":{
                            "legaltags":[
                                "opendes-public-usa-dataset-1"
                            ],
                            "otherRelevantDataCountries":[
                                "US"
                            ],
                            "status":"compliant"
                        },
                        "id":"opendes:doc:1934c51244af4952a7b60c41173e174e",
                        "acl":{
                            "viewers":[
                                "data.default.viewers@opendes.testing.com"
                            ],
                            "owners":[
                                "data.default.owners@opendes.testing.com"
                            ]
                        },
                        "type":"well-master",
                        "version":1587773484611490
                    },
            {
                            "data":{
                                "Data.IndividualTypeProperties.DataSourceOrganisationID":"srn:master-data/Organisation:TNO:",
                                "Data.IndividualTypeProperties.VerticalMeasurements":[
                                    {
                                        "VerticalCRSID":"srn:reference-data/VerticalCRS:MSL:",
                                        "VerticalMeasurementID":"Kelly Bushing",
                                        "VerticalMeasurementPathID":"srn:reference-data/VerticalMeasurementPath:Elevation:",
                                        "VerticalMeasurementTypeID":"srn:reference-data/VerticalMeasurementType:Kelly Bushing:",
                                        "VerticalMeasurement":36.6,
                                        "VerticalMeasurementUnitOfMeasureID":"srn:reference-data/UnitOfMeasure:M:"
                                    }
                                ],
                                "SpatialLocation":[
                                    "Coordinates=['x=3.51906683, y=55.68101428'], SpatialGeometryTypeID='srn:reference-data/SpatialGeometryType:Point:', VerticalCRSID='srn:reference-data/VerticalCRS:MSL:', HorizontalCRSID='srn:reference-data/HorizontalCRS:WGS84:', HeightAboveGroundLevelUOMID='srn:reference-data/UnitOfMeasure:M:'"
                                ],
                                "Data.IndividualTypeProperties.FacilityName":"A05-01",
                                "WellName":"Camron-01",
                                "Data.IndividualTypeProperties.FacilityNameAlias":[
                                    {
                                        "AliasName":"A05-01",
                                        "AliasNameTypeID":"srn:reference-data/AliasNameType:Name:"
                                    },
                                    {
                                        "AliasName":"8438",
                                        "AliasNameTypeID":"srn:reference-data/AliasNameType:UWI:"
                                    }
                                ],
                                "Data.IndividualTypeProperties.CountryID":"srn:master-data/GeopoliticalEntity:Netherlands:",
                                "Data.IndividualTypeProperties.SpatialLocation":[
                                    {
                                        "HorizontalCRSID":"srn:reference-data/HorizontalCRS:WGS84:",
                                        "VerticalCRSID":"srn:reference-data/VerticalCRS:MSL:",
                                        "HeightAboveGroundLevelUOMID":"srn:reference-data/UnitOfMeasure:M:",
                                        "Coordinates":[
                                            {
                                                "x":3.51906683,
                                                "y":55.68101428
                                            }
                                        ],
                                        "SpatialGeometryTypeID":"srn:reference-data/SpatialGeometryType:Point:"
                                    }
                                ],
                                "UWI":"8438",
                                "Data.IndividualTypeProperties.FacilityOperator":[
                                    {
                                        "FacilityOperatorOrganisationID":"srn:master-data/Organisation:Amarada Hess:"
                                    }
                                ],
                                "Data.IndividualTypeProperties.OperatingEnvironmentID":"srn:reference-data/WellOperatingEnvironment:OFF:",
                                "FacilityEvent":[
                                    "FacilityEventTypeID='srn:reference-data/FacilityEventType:SPUD:', EffectiveDateTime='1999-06-03T00:00:00'",
                                    "FacilityEventTypeID='srn:reference-data/FacilityEventType:DRILLING FINISH:', EffectiveDateTime='1999-07-02T00:00:00'"
                                ],
                                "ResourceID":"srn:master-data/Well:8438:",
                                "Data.IndividualTypeProperties.DefaultVerticalMeasurementID":"Kelly Bushing",
                                "Data.IndividualTypeProperties.BlockID":"srn:master-data/GeopoliticalEntity:A05:",
                                "x-geojson":{
                                    "geometries":[
                                        {
                                            "coordinates":[
                                                3.219067,
                                                55.481014
                                            ],
                                            "type":"point"
                                        }
                                    ],
                                    "type":"geometrycollection"
                                },
                                "ResourceSecurityClassification":"srn:reference-data/ResourceSecurityClassification:RESTRICTED:",
                                "ResourceTypeID":"srn:type:master-data/Well:",
                                "GeoLocation":{
                                    "lon":3.519067,
                                    "lat":55.681014
                                },
                                "Data.IndividualTypeProperties.FacilityEvent":[
                                    {
                                        "EffectiveDateTime":"1999-06-03T00:00:00",
                                        "FacilityEventTypeID":"srn:reference-data/FacilityEventType:SPUD:"
                                    },
                                    {
                                        "EffectiveDateTime":"1999-07-02T00:00:00",
                                        "FacilityEventTypeID":"srn:reference-data/FacilityEventType:DRILLING FINISH:"
                                    }
                                ],
                                "SpudDate":"1999-06-03T00:00:00+0000",
                                "Data.IndividualTypeProperties.FacilityState":[
                                    {
                                        "FacilityStateTypeID":"srn:reference-data/FacilityStateType:Abandoned:"
                                    }
                                ]
                            },
                            "kind":"opendes:osdu:well-master:0.2.1",
                            "namespace":"opendes:osdu",
                            "legal":{
                                "legaltags":[
                                    "opendes-public-usa-dataset-1"
                                ],
                                "otherRelevantDataCountries":[
                                    "US"
                                ],
                                "status":"compliant"
                            },
                            "id":"opendes:doc:1934c51244af4952a7b60c41173e174e",
                            "acl":{
                                "viewers":[
                                    "data.default.viewers@opendes.testing.com"
                                ],
                                "owners":[
                                    "data.default.owners@opendes.testing.com"
                                ]
                            },
                            "type":"well-master",
                            "version":1587773484611490
                        },
                {
                                "data":{
                                    "Data.IndividualTypeProperties.DataSourceOrganisationID":"srn:master-data/Organisation:TNO:",
                                    "Data.IndividualTypeProperties.VerticalMeasurements":[
                                        {
                                            "VerticalCRSID":"srn:reference-data/VerticalCRS:MSL:",
                                            "VerticalMeasurementID":"Kelly Bushing",
                                            "VerticalMeasurementPathID":"srn:reference-data/VerticalMeasurementPath:Elevation:",
                                            "VerticalMeasurementTypeID":"srn:reference-data/VerticalMeasurementType:Kelly Bushing:",
                                            "VerticalMeasurement":36.6,
                                            "VerticalMeasurementUnitOfMeasureID":"srn:reference-data/UnitOfMeasure:M:"
                                        }
                                    ],
                                    "SpatialLocation":[
                                        "Coordinates=['x=3.51906683, y=55.68101428'], SpatialGeometryTypeID='srn:reference-data/SpatialGeometryType:Point:', VerticalCRSID='srn:reference-data/VerticalCRS:MSL:', HorizontalCRSID='srn:reference-data/HorizontalCRS:WGS84:', HeightAboveGroundLevelUOMID='srn:reference-data/UnitOfMeasure:M:'"
                                    ],
                                    "Data.IndividualTypeProperties.FacilityName":"A05-01",
                                    "WellName":"Dupe-01",
                                    "Data.IndividualTypeProperties.FacilityNameAlias":[
                                        {
                                            "AliasName":"A05-01",
                                            "AliasNameTypeID":"srn:reference-data/AliasNameType:Name:"
                                        },
                                        {
                                            "AliasName":"8438",
                                            "AliasNameTypeID":"srn:reference-data/AliasNameType:UWI:"
                                        }
                                    ],
                                    "Data.IndividualTypeProperties.CountryID":"srn:master-data/GeopoliticalEntity:Netherlands:",
                                    "Data.IndividualTypeProperties.SpatialLocation":[
                                        {
                                            "HorizontalCRSID":"srn:reference-data/HorizontalCRS:WGS84:",
                                            "VerticalCRSID":"srn:reference-data/VerticalCRS:MSL:",
                                            "HeightAboveGroundLevelUOMID":"srn:reference-data/UnitOfMeasure:M:",
                                            "Coordinates":[
                                                {
                                                    "x":3.51906683,
                                                    "y":55.68101428
                                                }
                                            ],
                                            "SpatialGeometryTypeID":"srn:reference-data/SpatialGeometryType:Point:"
                                        }
                                    ],
                                    "UWI":"8438",
                                    "Data.IndividualTypeProperties.FacilityOperator":[
                                        {
                                            "FacilityOperatorOrganisationID":"srn:master-data/Organisation:Amarada Hess:"
                                        }
                                    ],
                                    "Data.IndividualTypeProperties.OperatingEnvironmentID":"srn:reference-data/WellOperatingEnvironment:OFF:",
                                    "FacilityEvent":[
                                        "FacilityEventTypeID='srn:reference-data/FacilityEventType:SPUD:', EffectiveDateTime='1999-06-03T00:00:00'",
                                        "FacilityEventTypeID='srn:reference-data/FacilityEventType:DRILLING FINISH:', EffectiveDateTime='1999-07-02T00:00:00'"
                                    ],
                                    "ResourceID":"srn:master-data/Well:8438:",
                                    "Data.IndividualTypeProperties.DefaultVerticalMeasurementID":"Kelly Bushing",
                                    "Data.IndividualTypeProperties.BlockID":"srn:master-data/GeopoliticalEntity:A05:",
                                    "x-geojson":{
                                        "geometries":[
                                            {
                                                "coordinates":[
                                                    3.819067,
                                                    55.781014
                                                ],
                                                "type":"point"
                                            }
                                        ],
                                        "type":"geometrycollection"
                                    },
                                    "ResourceSecurityClassification":"srn:reference-data/ResourceSecurityClassification:RESTRICTED:",
                                    "ResourceTypeID":"srn:type:master-data/Well:",
                                    "GeoLocation":{
                                        "lon":3.519067,
                                        "lat":55.681014
                                    },
                                    "Data.IndividualTypeProperties.FacilityEvent":[
                                        {
                                            "EffectiveDateTime":"1999-06-03T00:00:00",
                                            "FacilityEventTypeID":"srn:reference-data/FacilityEventType:SPUD:"
                                        },
                                        {
                                            "EffectiveDateTime":"1999-07-02T00:00:00",
                                            "FacilityEventTypeID":"srn:reference-data/FacilityEventType:DRILLING FINISH:"
                                        }
                                    ],
                                    "SpudDate":"1999-06-03T00:00:00+0000",
                                    "Data.IndividualTypeProperties.FacilityState":[
                                        {
                                            "FacilityStateTypeID":"srn:reference-data/FacilityStateType:Abandoned:"
                                        }
                                    ]
                                },
                                "kind":"opendes:osdu:well-master:0.2.1",
                                "namespace":"opendes:osdu",
                                "legal":{
                                    "legaltags":[
                                        "opendes-public-usa-dataset-1"
                                    ],
                                    "otherRelevantDataCountries":[
                                        "US"
                                    ],
                                    "status":"compliant"
                                },
                                "id":"opendes:doc:1934c51244af4952a7b60c41173e174e",
                                "acl":{
                                    "viewers":[
                                        "data.default.viewers@opendes.testing.com"
                                    ],
                                    "owners":[
                                        "data.default.owners@opendes.testing.com"
                                    ]
                                },
                                "type":"well-master",
                                "version":1587773484611490
                            },
                    {
                                    "data":{
                                        "Data.IndividualTypeProperties.DataSourceOrganisationID":"srn:master-data/Organisation:TNO:",
                                        "Data.IndividualTypeProperties.VerticalMeasurements":[
                                            {
                                                "VerticalCRSID":"srn:reference-data/VerticalCRS:MSL:",
                                                "VerticalMeasurementID":"Kelly Bushing",
                                                "VerticalMeasurementPathID":"srn:reference-data/VerticalMeasurementPath:Elevation:",
                                                "VerticalMeasurementTypeID":"srn:reference-data/VerticalMeasurementType:Kelly Bushing:",
                                                "VerticalMeasurement":36.6,
                                                "VerticalMeasurementUnitOfMeasureID":"srn:reference-data/UnitOfMeasure:M:"
                                            }
                                        ],
                                        "SpatialLocation":[
                                            "Coordinates=['x=3.51906683, y=55.68101428'], SpatialGeometryTypeID='srn:reference-data/SpatialGeometryType:Point:', VerticalCRSID='srn:reference-data/VerticalCRS:MSL:', HorizontalCRSID='srn:reference-data/HorizontalCRS:WGS84:', HeightAboveGroundLevelUOMID='srn:reference-data/UnitOfMeasure:M:'"
                                        ],
                                        "Data.IndividualTypeProperties.FacilityName":"A05-01",
                                        "WellName":"Naini-01",
                                        "Data.IndividualTypeProperties.FacilityNameAlias":[
                                            {
                                                "AliasName":"A05-01",
                                                "AliasNameTypeID":"srn:reference-data/AliasNameType:Name:"
                                            },
                                            {
                                                "AliasName":"8438",
                                                "AliasNameTypeID":"srn:reference-data/AliasNameType:UWI:"
                                            }
                                        ],
                                        "Data.IndividualTypeProperties.CountryID":"srn:master-data/GeopoliticalEntity:Netherlands:",
                                        "Data.IndividualTypeProperties.SpatialLocation":[
                                            {
                                                "HorizontalCRSID":"srn:reference-data/HorizontalCRS:WGS84:",
                                                "VerticalCRSID":"srn:reference-data/VerticalCRS:MSL:",
                                                "HeightAboveGroundLevelUOMID":"srn:reference-data/UnitOfMeasure:M:",
                                                "Coordinates":[
                                                    {
                                                        "x":3.51906683,
                                                        "y":55.68101428
                                                    }
                                                ],
                                                "SpatialGeometryTypeID":"srn:reference-data/SpatialGeometryType:Point:"
                                            }
                                        ],
                                        "UWI":"8438",
                                        "Data.IndividualTypeProperties.FacilityOperator":[
                                            {
                                                "FacilityOperatorOrganisationID":"srn:master-data/Organisation:Amarada Hess:"
                                            }
                                        ],
                                        "Data.IndividualTypeProperties.OperatingEnvironmentID":"srn:reference-data/WellOperatingEnvironment:OFF:",
                                        "FacilityEvent":[
                                            "FacilityEventTypeID='srn:reference-data/FacilityEventType:SPUD:', EffectiveDateTime='1999-06-03T00:00:00'",
                                            "FacilityEventTypeID='srn:reference-data/FacilityEventType:DRILLING FINISH:', EffectiveDateTime='1999-07-02T00:00:00'"
                                        ],
                                        "ResourceID":"srn:master-data/Well:8438:",
                                        "Data.IndividualTypeProperties.DefaultVerticalMeasurementID":"Kelly Bushing",
                                        "Data.IndividualTypeProperties.BlockID":"srn:master-data/GeopoliticalEntity:A05:",
                                        "x-geojson":{
                                            "geometries":[
                                                {
                                                    "coordinates":[
                                                        3.119067,
                                                        55.181014
                                                    ],
                                                    "type":"point"
                                                }
                                            ],
                                            "type":"geometrycollection"
                                        },
                                        "ResourceSecurityClassification":"srn:reference-data/ResourceSecurityClassification:RESTRICTED:",
                                        "ResourceTypeID":"srn:type:master-data/Well:",
                                        "GeoLocation":{
                                            "lon":3.519067,
                                            "lat":55.681014
                                        },
                                        "Data.IndividualTypeProperties.FacilityEvent":[
                                            {
                                                "EffectiveDateTime":"1999-06-03T00:00:00",
                                                "FacilityEventTypeID":"srn:reference-data/FacilityEventType:SPUD:"
                                            },
                                            {
                                                "EffectiveDateTime":"1999-07-02T00:00:00",
                                                "FacilityEventTypeID":"srn:reference-data/FacilityEventType:DRILLING FINISH:"
                                            }
                                        ],
                                        "SpudDate":"1999-06-03T00:00:00+0000",
                                        "Data.IndividualTypeProperties.FacilityState":[
                                            {
                                                "FacilityStateTypeID":"srn:reference-data/FacilityStateType:Abandoned:"
                                            }
                                        ]
                                    },
                                    "kind":"opendes:osdu:well-master:0.2.1",
                                    "namespace":"opendes:osdu",
                                    "legal":{
                                        "legaltags":[
                                            "opendes-public-usa-dataset-1"
                                        ],
                                        "otherRelevantDataCountries":[
                                            "US"
                                        ],
                                        "status":"compliant"
                                    },
                                    "id":"opendes:doc:1934c51244af4952a7b60c41173e174e",
                                    "acl":{
                                        "viewers":[
                                            "data.default.viewers@opendes.testing.com"
                                        ],
                                        "owners":[
                                            "data.default.owners@opendes.testing.com"
                                        ]
                                    },
                                    "type":"well-master",
                                    "version":1587773484611490
                                },
                        {
                                        "data":{
                                            "Data.IndividualTypeProperties.DataSourceOrganisationID":"srn:master-data/Organisation:TNO:",
                                            "Data.IndividualTypeProperties.VerticalMeasurements":[
                                                {
                                                    "VerticalCRSID":"srn:reference-data/VerticalCRS:MSL:",
                                                    "VerticalMeasurementID":"Kelly Bushing",
                                                    "VerticalMeasurementPathID":"srn:reference-data/VerticalMeasurementPath:Elevation:",
                                                    "VerticalMeasurementTypeID":"srn:reference-data/VerticalMeasurementType:Kelly Bushing:",
                                                    "VerticalMeasurement":36.6,
                                                    "VerticalMeasurementUnitOfMeasureID":"srn:reference-data/UnitOfMeasure:M:"
                                                }
                                            ],
                                            "SpatialLocation":[
                                                "Coordinates=['x=3.51906683, y=55.68101428'], SpatialGeometryTypeID='srn:reference-data/SpatialGeometryType:Point:', VerticalCRSID='srn:reference-data/VerticalCRS:MSL:', HorizontalCRSID='srn:reference-data/HorizontalCRS:WGS84:', HeightAboveGroundLevelUOMID='srn:reference-data/UnitOfMeasure:M:'"
                                            ],
                                            "Data.IndividualTypeProperties.FacilityName":"A05-01",
                                            "WellName":"Shankar-01",
                                            "Data.IndividualTypeProperties.FacilityNameAlias":[
                                                {
                                                    "AliasName":"A05-01",
                                                    "AliasNameTypeID":"srn:reference-data/AliasNameType:Name:"
                                                },
                                                {
                                                    "AliasName":"8438",
                                                    "AliasNameTypeID":"srn:reference-data/AliasNameType:UWI:"
                                                }
                                            ],
                                            "Data.IndividualTypeProperties.CountryID":"srn:master-data/GeopoliticalEntity:Netherlands:",
                                            "Data.IndividualTypeProperties.SpatialLocation":[
                                                {
                                                    "HorizontalCRSID":"srn:reference-data/HorizontalCRS:WGS84:",
                                                    "VerticalCRSID":"srn:reference-data/VerticalCRS:MSL:",
                                                    "HeightAboveGroundLevelUOMID":"srn:reference-data/UnitOfMeasure:M:",
                                                    "Coordinates":[
                                                        {
                                                            "x":3.51906683,
                                                            "y":55.68101428
                                                        }
                                                    ],
                                                    "SpatialGeometryTypeID":"srn:reference-data/SpatialGeometryType:Point:"
                                                }
                                            ],
                                            "UWI":"8438",
                                            "Data.IndividualTypeProperties.FacilityOperator":[
                                                {
                                                    "FacilityOperatorOrganisationID":"srn:master-data/Organisation:Amarada Hess:"
                                                }
                                            ],
                                            "Data.IndividualTypeProperties.OperatingEnvironmentID":"srn:reference-data/WellOperatingEnvironment:OFF:",
                                            "FacilityEvent":[
                                                "FacilityEventTypeID='srn:reference-data/FacilityEventType:SPUD:', EffectiveDateTime='1999-06-03T00:00:00'",
                                                "FacilityEventTypeID='srn:reference-data/FacilityEventType:DRILLING FINISH:', EffectiveDateTime='1999-07-02T00:00:00'"
                                            ],
                                            "ResourceID":"srn:master-data/Well:8438:",
                                            "Data.IndividualTypeProperties.DefaultVerticalMeasurementID":"Kelly Bushing",
                                            "Data.IndividualTypeProperties.BlockID":"srn:master-data/GeopoliticalEntity:A05:",
                                            "x-geojson":{
                                                "geometries":[
                                                    {
                                                        "coordinates":[
                                                            3.119067,
                                                            55.181014
                                                        ],
                                                        "type":"point"
                                                    }
                                                ],
                                                "type":"geometrycollection"
                                            },
                                            "ResourceSecurityClassification":"srn:reference-data/ResourceSecurityClassification:RESTRICTED:",
                                            "ResourceTypeID":"srn:type:master-data/Well:",
                                            "GeoLocation":{
                                                "lon":3.519067,
                                                "lat":55.681014
                                            },
                                            "Data.IndividualTypeProperties.FacilityEvent":[
                                                {
                                                    "EffectiveDateTime":"1999-06-03T00:00:00",
                                                    "FacilityEventTypeID":"srn:reference-data/FacilityEventType:SPUD:"
                                                },
                                                {
                                                    "EffectiveDateTime":"1999-07-02T00:00:00",
                                                    "FacilityEventTypeID":"srn:reference-data/FacilityEventType:DRILLING FINISH:"
                                                }
                                            ],
                                            "SpudDate":"1999-06-03T00:00:00+0000",
                                            "Data.IndividualTypeProperties.FacilityState":[
                                                {
                                                    "FacilityStateTypeID":"srn:reference-data/FacilityStateType:Abandoned:"
                                                }
                                            ]
                                        },
                                        "kind":"opendes:osdu:well-master:0.2.1",
                                        "namespace":"opendes:osdu",
                                        "legal":{
                                            "legaltags":[
                                                "opendes-public-usa-dataset-1"
                                            ],
                                            "otherRelevantDataCountries":[
                                                "US"
                                            ],
                                            "status":"compliant"
                                        },
                                        "id":"opendes:doc:1934c51244af4952a7b60c41173e174e",
                                        "acl":{
                                            "viewers":[
                                                "data.default.viewers@opendes.testing.com"
                                            ],
                                            "owners":[
                                                "data.default.owners@opendes.testing.com"
                                            ]
                                        },
                                        "type":"well-master",
                                        "version":1587773484611490
                                    }
    ],
    "aggregations":"None",
    "totalCount":1
};